function image(filepath){
    return "<img class=\"img-fluid rounded mx-auto d-block\" src=\"TemplateData/"+filepath+"\">"
}
function audio(name){
    return "<audio controls><source src=\"TemplateData/Music/"+name+".mp3\" type=\"audio/mpeg\"></audio>"
}

function beginGroup(href, name){
    return "<div class=\"card\" style=\"border-color: #63b6cf; \">\n<div class=\"card-header\" style=\"background-color: #8ac8db; \" data-bs-toggle=\"collapse\" href=\"#"+href+"\">\n<h4>"+name+"</h4>\n</div>\n<div id=\""+href+"\" class=\"collapse\">\n<div class=\"card-body\" style=\"background-color: lightblue\">\n"
}

function addCard(href, name, text){
    return "<div class=\"card\">\n<div class=\"card-header\" style=\"background-color: #eaeaea\" data-bs-toggle=\"collapse\" href=\"#"+href+"\">\n<h6>"+name+"</h6>\n</div>\n<div id=\""+href+"\" class=\"collapse\">\n<div class=\"card-body\">\n"+text+"\n</div>\n</div>\n</div>\n"
}


function closeCard(){
    return "</div>\n</div>\n</div>\n"
}

function section(href, name, subNames, subText){
    var out = beginGroup(href, name)
    for (var i = 0; i < subNames.length; i++)
        out+=addCard(href+i, subNames[i], subText[i])
    out+=closeCard()
    return out
}

function music(){
    const songNames = ["ChampionsPrelude", "Tranquility", "AnniversaryReturn", "VagrantWarrior", "TropicalSunshine", "GlacialRespite", "SubterranSoldier", "UnchartedVerdant", "TerrorAutomata", "AtavisticInstincts", "UrbanOnslaught", "FateOfTheFuture", "Serenity"]
    const names = ["Champion’s Prelude (Intro)", "Tranquility (Village)","Anniversary Return (Level 1)","Vagrant Warrior (Level 2)","Tropical Sunshine (Level 3)","Glacial Respite (Level 4)","Subterran Soldier (Level 5)","Uncharted Verdant (Level 6)","Terror Automata (Level 7)","Atavistic Instincts (Level 8)","Urban Onslaught (Level 9)","Fate of the Future (Boss)","Serenity (Epilogue)"]
    const descriptions = [
        "Champion’s Prelude was the last song composed. It combines elements from the village theme and the boss theme, with an intermediate theme connecting the two, representing the cats. It has the most instruments out of all the songs, coming in at 7 synths and 3 drums.",
        "In contrast to Champion's Prelude, a remix of this song, Tranquility was the first song I created for Cat and Mouse 4. I wanted to start with a song for the first stage, but it ended up being too calm and peaceful for an exciting adventure, so I repurposed it for the village. Music was all created using the free Waveform 12, and played on a Yamaha electric piano as MIDI input.",
        "This was the second song composed, being a quick and bouncy theme. I named this song after the date of Cat and Mouse releases, with Cat and Mouse 4 releasing exactly 52 weeks after Cat and Mouse 3, which was released on August 20, 2022.",
        "I composed this very early, with little experience in composing, so this song is not as good as the others. I went for a slow song that represents the heat and aridity of a desert.",
        "Similarly to Vagrant Warrior, I wanted a slow song, but a peaceful one that feels like relaxing at a beach. Tropical Sunshine has slow percussion and some tropical-sounding instruments to help create this feeling.",
        "This is one of my favorite songs, using many sustain effects to create sounds that stay active for long times. At this point in composing, I started to create the bassline first, and then build the melody on top of that, in contrast to building the melody first and the bassline after. It made making Glacial Respite, and the songs that came after it, a lot easier.",
        "The instruments on Subterran Soldier are what I imagine a noble soldier fighting underground would sound like: a low, gravelly sound, with a powerful backing bassline. Many of the other songs use various percussive instruments, like tambourines, but I stayed with a standard drumset with this one.",
        "This jungle theme mixes many percussive instruments, making especially good use of differently-pitched toms. Other instruments include the claves and the maracas. I wanted this song to feel like an expedition to an unexplored part of the world, with feelings of bravery, but also a sense of the unknown.",
        "This song was very fun to write. I used a metronome to create the ticking sound, along with a subtle bass drum that sounds like a slow heartbeat. The sustained sounds in this song intentionally clash with each other- I just played random chords and put it in as music.",
        "Atavistic Instincts is named after the instincts that ancient cats used to have, before their decline. It’s an ancient song that invokes a sense of prehistoric power that only ancestors would have.",
        "This is the song in the last level, heard right before the boss fight. It’s meant to invoke the courage that you’ll need to have in order to face the king of the cats. This one took me an especially long time to make, as being almost done with music made me lose my focus multiple times.",
        "The boss theme is a remix of Tranquility! With faster tempo and more aggressive instrumentation and percussion, Fate of the Future is a backdrop for a heart-pounding battle against the mighty ruler of the cats, or a powerful developer hidden in a cave. Fun fact: although this song was used for both the final boss and the secret boss, I had planned for the secret boss to have his own theme that mixed in elements from songs I like: specifically Moonstruck Blossom from Kirby Triple Deluxe. However, Fate of the Future ended up being so good that I used it for both boss fights.<br><br>"+audio("FateOfTheFutureIntro"),
        "Serenity is a slower and even calmer version of Tranquility, representing the wizard, the first Cat King, being at peace at the end of the game. I like to imagine that after the events of the game, the wizard disappeared from the general public, but kept his watch over the land to ensure that peace lives on. One day, if serenity is threatened, a warrior will rise up and challenge the darkness, but for now, we are at peace."
    ]

    for (let i = 0; i < descriptions.length; i++) {
        descriptions[i] += "<br><br>"+audio(songNames[i])
    }

    var res = ""

    for (let i = 0; i < names.length; i++) {
        var href = "music"+i
        res+=addCard(href, names[i], descriptions[i])
    }
    return res
}


function armaments(){
    return section("staff", "Staff", 
    ["Old Staff", "Double Edge", "Battle Lance", "Perdition's Ferocity", "Binate Buster", "Triple Threat", "Remnant Javelin"], 
    ["With this new version of Cat and Mouse, I wanted to step away from swords being the first weapon the player uses. Staffs are the first melee weapons in Cat and Mouse 4, and serve as a “baseline” weapon, with above-average range. I used a long roll of gift wrap as a prop during animations, and swung it around to get a feel of how I would animate it. It felt a little silly to attack invisible enemies in my room, but it got results.",
    "Tier 2 armaments split base weapons in Cat and Mouse 4 into one of two styles. Tier 3 armaments add on to these styles, in one of four themes. The Double Edge adds onto the idea that staffs have two sides to attack with, with a blade on each side.",
    "This design splits from a staff, moving into a spear. Using only one side to attack adds some power, but it doesn’t get a speed buff like Double Edge.",
    "The “hellstaff” was originally meant to be a double-sided trident. While it does keep the design of having three prongs on either side, it doesn’t resemble a trident much, especially not the water theme tridents are usually associated with. The concept was split into two weapons: the double-sided Perdition’s Ferocity, and the traditional trident Triple Threat.",
    "This double-sided scythe is used by the final boss, fitting its mechanical theme. I took lots of inspiration from stick figure animations from the early 2010s, and this is certainly reminiscent of those animation styles. Whenever I equip this in-game, I can only imagine myself pulling off combo attacks on cats.",
    "This trident channels the power of water to blast away your enemies. I initially wanted its special to be a combo attack that hit multiple times, but I got lazy on the animations and decided on a single strong attack. While making this weapon, Azura from FE Fates came to mind, who is an elegant lance user themed around water.",
    "While designing weapons, I drew art for each one, along with describing what a special attack could be. The only thing I put down for the Remnant Javelin is “YEEEEEEEET”. So there we have it: a throwable javelin. I had a little trouble drawing the sprite, as the prongs on the back of the javelin made perspective drawing difficult for me."]) +
    section("bow", "Bow", 
    ["Wooden Bow","Compound Bow","Recurve Bow","Recurrence Relation","Steelpiercer","Hailstorm","Noble Greatbow"], 
    ["Although Cat and Mouse 4 starts with a staff instead of a sword, I didn’t want to move away from the bow and arrow, which I consider integral to the feeling of Cat and Mouse: a somewhat fantasy adventure that starts with basic gear, and gets more advanced the more we go.",
    "Compound and Recurve bows share very similar models, and I wouldn’t consider there to be much difference between them. Both upgrades have very similar stats. They really begin to diverge in Tier 3, but Tier 2 has little divergence. Other weapons with little Tier 2 divergence are Shields and Knuckles.",
    "Initially, bows were usable while moving, leading to a funny animation of the mouse sliding across the ground, as the animation has the mouse standing upright without leg movement. Bows (and certain Flit) are the only weapons that are not usable while moving.",
    "My fellow programmers, rejoice at the name of this bow! Recurrence Relation is somewhat inspired by a Destiny 2 weapon of a similar name, Iterative Loop. This compound bow is used by warriors of the future, being enhanced by technology to be strong and fast.",
    "The compound bow is themed around technology, which this metallic crossbow embodies. I have always found the mechanisms of crossbows fascinating. Having spent too much time on Stickpage when I was younger, this weapon was inspired by Stick War’s Albowtross, the Flying Crossbowmen.",
    "This bow was very fun to design, especially the ice on the back of the weapon. As a magical armament, Hailstorm embodies the element of ice, freezing enemies with its special. It doesn’t have any particular inspiration, but I found the idea of a freezing bow to be interesting.",
    "The Noble Greatbow was once wielded by a hero of a forgotten time. Its special, Sniper Shot, pays homage to Fire Emblem, where snipers pick off opponents with powerful bows. Unlike FE, the Noble Greatbow is slower, but its special has the power to eliminate many opponents in one shot."]) +
    section("knuckles", "Knuckles", 
    ["Hand-to-Hand","Bladed Gloves","Spiked Gloves","Atrocity","Brutal Grappler","Heaven's Gaze","Perfect Balance"], 
    ["Knuckles and Shields are my favorite armaments in this game. Knuckles provide fast damage, with each blow being weak individually, but making up for it with low cooldowns. Maybe I’ve spent too long watching stick figure fight animations. Knuckles were very difficult to balance, as low damage did very little against enemies with high defense.",
    "Bladed and Spiked Gloves have little difference, but it really ramps up in Tier 3. Bladed Gloves take inspiration from ninja wrist guards from a video game I’ve played once. In Cat and Mouse 4, the blades extend from the knuckles, instead of from the forearms.",
    "These resemble the gloves of Knuckles the Echidna, having two spikes on either fist. While the Bladed Gloves are themed more towards using slicing to inflict extra damage, the Spiked Gloves (and its Tier 3s) are themed more towards raw punches and brute force.",
    "This weapon was originally named “The Scar”, taking its name from its shape. If it were smaller, it would resemble a large scar on a hand. The inspiration is pretty obvious. Besides that, its special, Behemoth Rend, is based on Destiny 2’s Berserkers, who have the ability to fire energy waves from dual blades while channeling Bladefury.",
    "These gloves were made to embody the terror and mercilessness found in the cats’ factories. Made using technology salvaged in these factories, Brutal Grapplers automatically deal retribution to any enemy that gets too close, with a huge punch. The flavor text “A single blow is all you need” is a pretty obvious One Punch Man reference.",
    "Heaven’s Gaze is wielded by the sleeping developer. One of my favorite armaments, this is a magic-infused version of the base Hand-to-Hand, being faster and stronger. In early designs, Divine Intervention was the name of the weapon, with the special name being “Seraphim Skystrike”, but it was eventually changed. Its special (and special effect) is based off of Fighter Kirby’s Rising Break uppercut.",
    "Yin and Yang are fixed to your fists! This weapon was inspired by Angry Birds Epic, an old turn-based RPG where the birds travel across the land, fighting pigs, to get their eggs back. The white bird Matilda has an item combo of yin and yang, with a set bonus also called Perfect Balance."]) +
    section("shield", "Shield", 
    ["Rusted Shield","Battle Shield","Light Shield","Iterative Immortality","Rocket Science","Safeguard's Vigil","Astasia"], 
    ["The complete opposite to the short ranged and fast Knuckles, Shields have high range and high individual damage and knockback, but suffer from long cooldowns. As with Knuckles, Shields were very difficult to balance, as they would one-shot many lower-level enemies. Shields differ from other armaments, as they provide a slight momentum boost when attacking.",
    "There’s very little difference between Battle Shields and Light Shields. Theme-wise, Battle Shields focus more on bringing the fight to the enemy, with a strong offense. Tier 3 Battle Shields are offense-oriented, with little in the way of utility.",
    "Light Shields are themed around defense, but their reduced weight means less cooldown and faster attacks. Tier 3 Light Shields are built much more around utility, with power to knock enemies back and debuff enemies.",
    "Similarly to the Recurrence Relation bow, Iterative Immortality is a code reference, in complete opposite to recursion. This shield initially had a much different design, having a circular shape that resembled a fried egg, and was thrown instead of shooting projectiles. The theme of immortality would have the shields regenerate after being thrown.",
    "Rocket Science is definitely my favorite weapon. One of my favorite things to do in games is to find ways to move around quickly, and Rocket Science’s extra swing speed provides a burst of momentum allowing you to fly across stages. Jet Breacher is inspired by Jet Kirby’s Jet Burst, which fires a burst of energy forwards.",
    "This shield’s wings were very fun to design and model. Safeguard’s Vigil is the “light” side of magic, and is a defensive weapon that knocks enemies back with its special. This shield originally looked like a Minecraft chestplate, but thankfully I changed the design.",
    "This shield is the Yin, symbolizing passivity, but also darkness and the cold. The name means “a lack of stasis”, or rather, unbalance: darkness without the light. Yin’s special, Antumbra, reflects Yin, making enemies weaker and slowing them down."]) +
    section("flit", "Flit", 
    ["Kunai","Auto Launcher","Shuriken","Thousand Stars","Blade Launcher","Diametric Doom","Return to Sender"], 
    ["The Flit were originally all called Kunai, but the name was changed and Kunai remained the first weapon in the category. Unlike Bows, Flit are able to be used while moving, befitting their style of a low-damage but fast weapon type.",
    "Launchers break the Flit standard of being usable while moving. It was hard to balance Launchers- on paper, fast fire rate and same damage as Shurikens was an advantage, but it was hard to balance that against the disadvantage of having to stay still while firing. Launchers are inspired by Helmet Heroes Cowboys, who use guns that make players stay still while firing.",
    "Shuriken are a returning item, present in every Cat and Mouse to date. Unlike launchers, Shuriken and its Tier 3s keep the lightweight style of Flit, being usable while moving. When I would younger, I had a drawer filled with origami shuriken, which were used in the original Cat and Mouse.",
    "This laser cannon is based off of Laser Cannon from the Bloons Tower Defense series, being able to pierce through multiple enemies and having a high fire rate with fast projectiles. I had initially wanted a long, continuous laser as its special, similar to the Ray of Doom from the same series, but decided on a single shot, and left the multi-hit continuous damage to the Blade Launcher.",
    "Similarly to Thousand Stars, the fully-automatic Blade Launcher is based off of Bloons Tower Defense’s Blade Shooter, short-range towers that attack with a burst of saw blades. I had intended for its special attack to be an overclock that increased damage for a short duration, but it ended up being replaced by a continuous stream of shots.",
    "These circular chakrams came to my attention during Kirby and the Forgotten Land, where Kirby has an upgraded Copy Ability letting him use chakrams as boomerangs to attack. Circumnavigator was once again BTD inspired, specifically by the Glaive Lord, who attacks with orbiting glaives. It was pretty fun to code, using sinusoidal functions to determine the coordinates of the orbiting chakram.",
    "The boomerang makes its return! It first flies forward, and then backwards, letting you retreat and attack at the same time. As with all Tier 3 Flit, it is BTD inspired, this time by the Boomerang Monkeys who attack using boomerangs."]) +
    section("sword", "Sword", 
    ["Rusted Sword","The Twins","Scimitar","The Subsequent","Duality","Rainbow Sword","Covert Valiance"], 
    ["Swords are largely the same as Staff, and play the same role as a moderate attack speed melee weapon. In the case of Swords, they are slightly stronger and faster, but have less range to compensate.",
    "Two daggers, one in each hand. In original concepts, I had intended for Tier 2 armaments to have special attacks as well, but I decided that would take too long, especially with regards to animations. The Twins would have had a multi-hit flurry attack, or a ranged dagger throw.",
    "This curved sword has no particular inspiration, but it is based off of stereotypical pirate swords. It keeps the theme of being a single sword, having a longer range but longer cooldown than The Twins.",
    "This is just the natural progression of swords. The Rusted Sword has one blade, The Twins has two blades, and so The Subsequent has four. Just like Atrocity, its Quad Doom draws inspiration from Destiny 2’s Berserkers’ ability to fire sword beams.",
    "Duality was one of my favorite weapons to design, especially its Amalgam Cleave. Duality is inspired by various weapons across media with the ability to combine into a stronger version- the one that comes to mind is Final Fantasy’s Fusion Sword, which combines six blades into a large sword.",
    "Rainbow Sword, returning once again! The fourth Rainbow Sword looks like its second iteration, but glows brighter and has a gold and black hilt. A similar version appears in the Kirby series, which is what this weapon is inspired by. Fun fact: the third Rainbow Sword, of which a statue is found on the right side of the village, was meant to resemble Morpho Knight’s Doomblade.",
    "This katana was used by a great sensei who taught many ninjas. As with Atrocity, the inspiration is pretty clear. Covert Valiance’s dash attack, Silencing Strike, is a reference to Ninja Kirby’s dash attack, Stealth Slash."])
}

function adornments(){
    return section("tier1", "Tier 1", 
    ["Sweatband","Jade Bracelet","Thin Helmet","Meat Skewer"], 
    ["This is the most self-explanatory adornment-  a simple red headband. When modeling adornments, I didn’t have much of a plan, and just modeled whatever came to mind, attached it somewhere on the player model, and came up with descriptions afterwards.",
    "The bracelet and the sweatband were very easy to model. Both of those are simply short cylinders. As for stats, I assigned stat points to adornments based on their theme. Tier 1 Adornments have a stat total of 2, Tier 2 with 3, Tier 3 with 5, and most Tier 4 with 4.",
    "A simple helmet. I was considering adding more headgear (besides the crown) later on, but the model might have conflicted with the helmet, so I decided not to.",
    "A delicious skewer of meat. In the original Cat and Mouse, this is meat from an unlucky cat, roasted over fire, and seasoned with cumin. Delicious?"]) +
    section("tier2", "Tier 2",
    ["Training Weight","Shoulder Pads","Bean Charm","Neon Visor"], 
    ["It was hard to figure out a place to attach the Training Weights to, but I ended up attaching them to the legs, similar to Rock Lee’s ankle weights. I had intended to make them decrease the speed of the user in addition to increasing strength, but decided against having gear that reduced stats.",
    "These shoulder pads were fun to make. Being new to Blender, I had to look up a bunch of guides to figure out how to leave one side as empty.",
    "The Bean Charm resembles an Among Us crewmate, which is what it is based upon. When I modeled it after a crewmate, it looked too silly in serious scenes, so I removed the distinct “helmet”, leaving only the shape.",
    "Tactical visor activated! The Neon Visor looks similar to Soldier: 76’s visor from Overwatch. Additionally, it is also inspired by a few stick fighters from the era of Stickpage and Rock Hard Gladiators."]) +
    section("tier3", "Tier 3",
    ["Coffee Talisman","Lucky Jacket","Upper Guard","Winged Boots"], 
    ["The almighty Duke plushie makes its way into Cat and Mouse! These plushies are granted to only the most worthy of Java users. I learned how to create these in August of 2021, and they seem to be a decent way of adding flair to a room.",
    "“Step 1: be lucky” is a catchphrase I found, and one of my favorite running jokes about having all luck and no skill. This adornment is a gray jacket I wore for the better part of high school and community college.",
    "This is a standard chestplate, augmented with technology to better protect the user. The line on the front resembles Genji’s visor from Overwatch, except in orange color.",
    "These boots are inspired by various winged items, but the winged sandals of Hermes are the ones giving the most inspiration. The boots let the player move faster, referencing the speed Hermes has as a messenger."]) +
    section("tier4", "Tier 4",
    ["Sovereign Crown","Bottled Cloud","Contestant Balloons","Dream Developer Vestment"], 
    ["Congratulations- you’ve won Cat and Mouse 4! But there’s still things to do, such as taking on the hidden Tier 4 Adornments, which are locked behind achievements.",
    "Tier 4 adornments were initially supposed to provide some kind of boost, in addition to stat boost. The cloud-in-a-bottle originally enabled double jumping, but I was worried that it would take away from combat, so it was scrapped.",
    "Long live the Mighty Polymorphers, and long live Winner POV! The real-life equivalent of these balloons were given to my team and me during the Spring 2023 Pacific Northwest International Collegiate Programming Contest, where I led Sierra College in our first-ever round. The balloons are only obtainable by fighting me in-game.",
    "The Dream Developer Vestment is my blue jacket, and it is obtained by completing every single achievement. The very last adornment in Cat and Mouse 4, it gives a point to every stat, with three points to Luck. If you see a blue jacket at an ICPC, come and say hi!"])
}


function about(){
    const names = ["About the Cat and Mouse series", "Cat and Mouse 2", "Cat and Mouse 3", "Cat and Mouse 4"]
    const descriptions = [
        "Cat and Mouse first began as a real-life game that my childhood friends and I played. We would pretend to be mice, and devised gameplay based around fighting imaginary cats, and throwing things around to fight them. Once, we put some blue painter’s tape in a rectangle at a doorstep, pretending that it was a trap for cats to step in. We would also use a Kirby plush, which we pretended was our “ally” in the fights.",
        "Seven years ago, in middle school, I made Cat and Mouse into a computer game, using Scratch. The player would traverse four levels (although these were just flat ground with enemies spawning) to fight a boss at the end. I didn’t make many updates to this game, with the only update being the addition of animations to the character that ended up breaking the collision detection system.<br><br>Gameplay was heavily inspired by Helmet Heroes, an old Flash MMO/RPG that I played in elementary school and all throughout middle school. I even set the background music to one of the level soundtracks from Helmet Heroes. This was my last big game on Scratch, and I don’t think I went back into it after I released the game, with most of my efforts going instead to studying. It was only after I found my love of computer science in my junior and senior years at high school did I return to programming.<br><br>"+image("About/cm2.png"),
        "I didn’t go back to the idea of Cat and Mouse until Summer 2022, during which one of my friends hosted a game jam. Although there were only three submissions (mine clearly being the best out of all of them), it was a great opportunity for me to further explore game development in Java.<br><br>Previously, I had made simple 2D platformers using Java, with my first game being Pushing Your Buttons, a platformer in which the terrain was made out of blocks, and could be changed by clicking. It has an unfinished sequel, with gameplay being complete, but I never got around to designing levels.<br><br>Cat and Mouse 3 was a huge stepping stone, as I moved away from working with tile platformers and moved into hand-drawn digital art for levels, instead of being solely squares. Much of my time was spent not only on code, but on making every background and foreground distinct and well-designed. Cat and Mouse 3 was an amazing learning experience, and really showed how easy it is to learn, if I’m interested in what I’m doing.<br><br>"+image("About/cm3.png"),
        "Unity is taught as part of the Code Ninjas curriculum. Although I already have seen the curriculum, wanting to better understand Unity, I took it upon myself to explore what Unity has to offer, to better understand and teach it to my students. I didn’t spend much time during the school year, as all of my effort was being put into passing Circuitry, but I got into Unity as soon as the year ended and I was free.<br><br>The early prototype for Cat and Mouse 4 reused sprites from Cat and Mouse 3, including the 2D player sprites. As I kept thinking about the game, I realized that I had too many ideas for the game that couldn't be done justice with 2D sprites alone, so I broadened my horizons and explored 3D modeling in Blender. I went overboard on the art, drawing every background and foreground, with many stages having five different layers of art. As for music, I decided to compose my own, as I want to share this game with people without generic free music or taking music from other media.<br><br>This game cost me nothing to make, and it will cost you nothing to play. Game development will remain just a hobby for me, and I have no intention to make any money from my creations. This is my greatest game yet, and I’ve learned a lot from making it. I hope you enjoy playing Cat and Mouse 4!",
    ]

    var res = ""

    for (let i = 0; i < names.length; i++) {
        var href = "about"+i
        res+=addCard(href, names[i], descriptions[i])
    }
    return res
}

function design(){
    const names = ["Unity - 1 week", "Blender - 3 weeks", "Unity - 2 weeks", "Krita - 3 weeks", "Unity - 3 weeks", "Waveform and Audacity - 1 week", "WebGL build and web design - 1 week"]
    const descriptions = [
        "I first began this game as a 2D recreation of Cat and Mouse 3, but wanted to make it much more than that. I started scripting certain attacks, but as I kept working, I realized that the Cat and Mouse 3 style of attacking, in which the player wouldn’t have an animation, and instead the weapon would just swing in front of the player, wouldn’t do the game justice. So I went to Blender to learn 3D modeling.",
        "I had a lot of fun learning Blender. This has been my first ever time doing anything related to 3D modeling, and I think I did a pretty decent job. I modeled the player at first, modeling it after what I imagined a stick figure might look like in three dimensions, and added ears and a snout for a distinctive mouse shape. Afterwards, I had to research how to attach items to the character, with a lot of help from some friends, and spent time modeling the armaments and adornments. The enemy model was very easy to make, as it is the same as the player model, just with a different color scheme and shorter, pointy ears.<br><br>The animation process took the longest. Animations had to be created for movement, jumping, falling, and every single attack. While I was able to reuse many animations, especially with Knuckles and Shields, I wanted attacks to have distinct animations to set them apart from others in their tier. After this, it was back to Unity to import everything.<br><br>"+image("Design/blender.gif"),
        "This Unity stretch started with the most painful debugging of my life. After I spent time putting the animations together, and linking attacks to their respective animations, I found that the player’s head and items would deform, as if stretched. Looking online gave no help, as I wasn’t able to properly describe the problem, and other people’s past responses didn’t work. It turns out that I had deformed many of the bones in my armature, which led to the model stretching weirdly. Annoyingly enough, this didn’t appear in Blender, where animations played perfectly, so I couldn’t have noticed it when I was working on animations. After a few adjustments in Blender, I was good to keep coding.<br><br>"+image("Design/boing.gif")+"<br>Next, I designed a simple level to test gameplay on. I added the player model with some controls for movement and attacking, and added an enemy to try my attacks on. With a lot of the code complete, I got to work on art.<br><br>"+image("Design/thisissparta.gif"),
        "All art was drawn in Krita, with a Wacom tablet. This was a long and tedious process, but I often found it relaxing to sit there, with some music and soda, making art for hours on end. The level I spent the most time on, and my favorite, was Level 5, and you’ll see why once you get to that level.<br><br>Each level has three layers of art. Just like Cat and Mouse 3, it has foreground and background, but this time, the background is split into four different layers. The foremost is the immediate background, which is on the same distance from the camera as the foreground, player, and enemies, but is rendered behind those. After that, there are two layers of background moving in parallax, and one final background for the sky, also moving in parallax. In Unity, I made the effect by simply placing the backgrounds away from the camera in perspective view, with the sky background being the farthest away.<br><br>"+image("Design/perspective.png"),
        "With art done, I finished code for moving between levels, as well as saving progress when the page is closed. The village and NPCs were coded, with dialogue needing some extra art to make. Weapons stats were selected, their behaviors coded, and put into the Shop, alongside adornments. Achievements took a decent chunk out of this time as well, and a lot of debugging had to be done there. The village and boss fight took up a lot of this coding time, as the boss has extra behaviors that differentiate it from standard enemies, and the village is full of interactables.<br><br>Even after the code was finished, I had to spend a lot of time just balancing the game, and making sure that nothing was overpowered or underpowered. I found this to be tougher than the code itself. To help with balancing, I added code to enemy spawners to control how much health enemies would have, alongside adding defense to cats to raise their effective health.",
        "I had expected that composing would take three weeks or more, but I ended up composing all 13 songs within the span of 5 days! I used the free Waveform 12 software, and connected a Yamaha electric piano to it, using the piano as a MIDI controller. I noodled around on the piano, seeing what sounded good, and when I liked something, I would record it and build off of it to make a full song. In the end, I devised a workflow of creating the bassline, adding percussion with instruments themed around the current level, and finally creating a melody.<br><br>"+image("Design/setup.png")+"<br>"+image("Design/waveform.png")+"<br>After composing, I also worked on sound effects using Audacity. Most sound effects I found online from Pixabay, a sound effect repository, and combined different sounds with each other, along with effects from Audacity, to make sounds for using weapons and taking damage.<br><br>"+image("Design/audacity.png")+"<br>I then put everything into the game, with only a few new pieces of code for controlling when music would play. With this, Cat and Mouse 4 gameplay was done.",
        "The very last thing I needed to do was to compile everything and put it online for everyone to enjoy. Before I did that, I decided to add a difficulty selector, as I realized that the game might be too difficult. I set the current game as the hard mode, and added a normal mode that was easier to play. Afterwards, I compiled into a WebGL build, which I then changed the formatting on to become this website. This website was built directly on top of a WebGL build! After that, all that was left to do was to upload it, and Cat and Mouse 4 was finished!"
    ]

    var res = ""

    for (let i = 0; i < names.length; i++) {
        var href = "design"+i
        res+=addCard(href, names[i], descriptions[i])
    }
    return res
}

function levels(){
    const names = ["Village", "Plains (Level 1)", "Desert (Level 2)", "Beach (Level 3)", "Mountain (Level 4)", "Cave (Level 5)", "Jungle (Level 6)", "Factory (Level 7)", "Past (Level 8)", "City (Level 9)", "Final Boss", "Hidden Boss"]
    const descriptions = [
        "I designed the village to be a haven for mice, thriving without fear of cat attacks. The village was only an addition to Cat and Mouse 3, as previous versions only had “hideouts”, but nothing like a large village. I had originally thought that NPCs would, like their Cat and Mouse 3 counterparts, be static sprites, but as I got into 3D modeling I decided to repurpose the player model to be an interactable NPC as well.<br><br>"+image("Levels/cm3village.png")+"<br>The shop and achievements screens were time-consuming to code, especially the shop, with its multiple pages, covering armaments and adornments. I made the shop backgrounds very late into the game’s development, and for the vast majority of the game, the background was a very simple placeholder sprite, composed of a bunch of rectangles that differentiate where sections start and end.",
        "Grass, grass, grass. Every computer scientist hates grass, but I stayed strong despite the weird green stuff. All of the grass here was hand drawn using upwards brush strokes in Krita.<br><br>The stage with the NPCs, the one that’s above the cat hideout, was meant to also include some kind of treasure chest that would give money or an item of some kind, but I got too lazy and just had it connect to the top of the cat hideout.<br><br>The hideout has a very similar-looking level in Cat and Mouse 3, with an underground section with a brown background.<br><br>"+image("Levels/cm3cave.png"),
        "Although I had planned to make a sand-themed level, it was only later that I decided to add pyramids to it. Stage 3 and 4 of the desert level were my favorites to design, and I spent a lot of time on the vases and bottles inside to add some flair to the otherwise empty rooms. Other than that, the sand was pretty easy to draw, and the sandy dunes gave some dynamic terrain after the mostly flat Plains level.<br><br>"+image("Levels/vases.png"),
        "I had never known that drawing water would be so fun. My water was made using blue-greens, with various shades depending on depth, and finished with almost-transparent layers of white and blue at the very top.<br><br>"+image("Levels/water.png")+"<br>With two sand levels right after each other, I didn’t want it to get repetitive, so I decided to add a boardwalk-like section, with a bridge connecting between two parts of the beach.",
        "Lots of mountains in the background for this level. When designing this level, I didn’t think about adding snow, but it came naturally as I made the art for this level. It was only after I had already finished the level did I realize that Krita came with mountain stamps, which I could have used instead of hand drawing each background mountain.<br><br>"+image("Levels/mountains.png"),
        "If it’s not blatantly obvious, I had a ton of fun drawing the crystals in the background. Each crystal has three shades: a main color, a lighter side, and a darker side. The crystals represent the magical presence of the wizard, who later grants you magical armaments in the fight against the cats.<br><br>I had wanted a cutscene that shows the player approaching the wizard while the rest of the cats were trying to convince the wizard to join their cause, but ended up not including it, as it breaks the theme of having cutscenes only after the end of each level.<br><br>The hidden boss's crystals are slightly lighter and more red, in contrast to the wizard's dark purple crystals.<br><br>"+image("Levels/crystals.png"),
        "The jungle was fun to make. It starts on the ground, but after climbing on trees, you fight on the canopy of the forest, before dropping back to the ground on the last level.<br><br>The parkour section is found by going upwards on the second level, with an alternate exit on the cloud above the regular stage exit. Testing this section was difficult, as I kept falling off and having to restart. It was originally themed around the jungle as well, with platforms originally being trees, but I realized that it didn’t fit the achievement and adornment unlocked, which is a cloud in a bottle.<br><br>"+image("Levels/parkour.png"),
        "The factory was similar to the desert pyramids, in that it has an indoors section with a detailed background. This, along with its background music Terror Automata, was one of my favorite levels to design. I went for an industrial look, tainted with the terrible crimes the cats did to the mice. Take a close look at the red and green lights in the background- is there anything hidden there?<br><br>I really wanted the factory to push the boundaries of what's realistic in this cat-and-mouse world, and expand upon why the Cat and Mouse 3 factory contained cheese inside it. Subtle hints at cats harvesting cheese have been provided with NPCs mentioning that cats don't each cheese throughout Cat and Mouse 3 and 4, but it really comes to light in the last factory.<br><br>"+image("Levels/cm3factory.png"),
        "Now we’re in the distant past, when cats were fearless and noble. You’re now fighting stronger cats, a far cry from their weaker present-day descendants. This level is meant to be reminiscent of the first level, the Plains, with all-natural grass and dirt.<br><br>In early designs, Cat and Mouse 4 was meant to be heavily themed around time travel, with traveling to the future to see the calamity if life were to continue the way that it was, and traveling to the past to prevent the start of the calamity. Even with the game’s release, there’s still a lot of time-based themes. The first two of every Tier 3 adornment is based around the future, with the first being based on futuristic technology, and the second based on industrial technology. The last two are based around the past, with the third based on magic (which is a bit of a stretch), and the last being based on weapons from ancient times.<br><br>"+image("Levels/armaments.png"),
        "The city was pretty hard for me to design, and even upon release it feels a little bland, level wise. I think I did a decent job on the background, but the stages themselves are pretty straightforward.<br><br>I had to think a lot about how to design the cats’ living places inside the city. I eventually decided on a somewhat dilapidated high-rise style, showing how far the cats have fallen from their ancestors.<br><br>"+image("Levels/city.png")+"<br>The palace, where the king is finally fought, was meant to be very lavish and clean, in stark contrast to the rest of the city. With the boss fight up ahead, the cats in this room are the strongest enemies by far and drop the most loot.",
        "The final boss, the king of the cats, is not a content ruler, but instead is saddened by the falling of catkind. He was born into nobility, but faced backlash after wanting to shut down the mouse factories. Though he was eventually able to shut down most, there were still some in production.<br><br>This boss fight was a tough one to balance. At first, I increased the boss’s defense stat, but this had an adverse effect of making fast and low-damage armaments, such as flit and knuckles, completely ineffective. I ended up removing this extra defense, and just increasing the boss's health a ridiculous amount.<br><br>"+image("Levels/healthbar.png"),
        "It’s me, the Dream Developer! I’m the secret boss! As with the Cat King, the Developer was hard to balance. Initially, I had him wear every single piece of gear, but I thought it more fitting to have only the jacket and balloon equipped. He still gains stat bonuses as if he has the other items equipped, though, and is a formidable, powerful, and handsome opponent.<br><br>I came up with this idea pretty much on a whim, after one of my friends asked to fight me as an enemy in a game sometime. I was meant to have custom attacks, such as thought bubbles and computer-related attacks, but ended up just equipping my favorite items onto the character and having that as a boss.<br><br>"+image("Levels/developer.png")
    ]

    var res = ""

    for (let i = 0; i < names.length; i++) {
        var href = "levels"+i
        res+=addCard(href, names[i], descriptions[i])
    }
    return res
}